name: Deploy CloudFormation Resources
on:
  workflow_dispatch:
    inputs:
      region:
        description: 'AWS Region'
        required: true
        default: 'ap-south-1'
jobs:
  cfn_deploy:
    name: Deploy CF stack to AWS
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ github.event.inputs.region}}
      - name: Create Artifactory Bucket if not already
        run: aws s3 mb s3://artifacts-test-week1 || echo "Bucket already exists"
      - name: Package Cloud Formation Resources
        run: aws cloudformation package --template-file cloudformation/lambda.yaml --s3-bucket artifacts-test-week1 --output-template-file outputTemplate.yaml
      - name: Deploy Cloud Formation Stack
        run: |
          aws cloudformation deploy --template-file outputTemplate.yaml --stack-name test9 --capabilities CAPABILITY_NAMED_IAM

